// Code generated by go-bindata. (@generated) DO NOT EDIT.
// sources:
// templates/cart.html
// templates/home.html
// templates/item.html
// templates/login.html
// templates/my_orders.html
// templates/old_cart.html
// templates/register.html
// templates/tag_search.html
// templates/layout/base.html
// templates/layout/footer.html
// templates/layout/nav.html
package views

import (
	"fmt"
	"io/ioutil"
	"os"
	"path/filepath"
	"strings"
)

// bindataRead reads the given file from disk. It returns an error on failure.
func bindataRead(path, name string) ([]byte, error) {
	buf, err := ioutil.ReadFile(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset %s at %s: %v", name, path, err)
	}
	return buf, err
}

type asset struct {
	bytes []byte
	info  os.FileInfo
}

// templatesCartHtml reads file data from disk. It returns an error on failure.
func templatesCartHtml() (*asset, error) {
	path := "/home/redhood/db_minor/templates/cart.html"
	name := "templates/cart.html"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// templatesHomeHtml reads file data from disk. It returns an error on failure.
func templatesHomeHtml() (*asset, error) {
	path := "/home/redhood/db_minor/templates/home.html"
	name := "templates/home.html"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// templatesItemHtml reads file data from disk. It returns an error on failure.
func templatesItemHtml() (*asset, error) {
	path := "/home/redhood/db_minor/templates/item.html"
	name := "templates/item.html"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// templatesLoginHtml reads file data from disk. It returns an error on failure.
func templatesLoginHtml() (*asset, error) {
	path := "/home/redhood/db_minor/templates/login.html"
	name := "templates/login.html"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// templatesMy_ordersHtml reads file data from disk. It returns an error on failure.
func templatesMy_ordersHtml() (*asset, error) {
	path := "/home/redhood/db_minor/templates/my_orders.html"
	name := "templates/my_orders.html"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// templatesOld_cartHtml reads file data from disk. It returns an error on failure.
func templatesOld_cartHtml() (*asset, error) {
	path := "/home/redhood/db_minor/templates/old_cart.html"
	name := "templates/old_cart.html"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// templatesRegisterHtml reads file data from disk. It returns an error on failure.
func templatesRegisterHtml() (*asset, error) {
	path := "/home/redhood/db_minor/templates/register.html"
	name := "templates/register.html"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// templatesTag_searchHtml reads file data from disk. It returns an error on failure.
func templatesTag_searchHtml() (*asset, error) {
	path := "/home/redhood/db_minor/templates/tag_search.html"
	name := "templates/tag_search.html"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// templatesLayoutBaseHtml reads file data from disk. It returns an error on failure.
func templatesLayoutBaseHtml() (*asset, error) {
	path := "/home/redhood/db_minor/templates/layout/base.html"
	name := "templates/layout/base.html"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// templatesLayoutFooterHtml reads file data from disk. It returns an error on failure.
func templatesLayoutFooterHtml() (*asset, error) {
	path := "/home/redhood/db_minor/templates/layout/footer.html"
	name := "templates/layout/footer.html"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// templatesLayoutNavHtml reads file data from disk. It returns an error on failure.
func templatesLayoutNavHtml() (*asset, error) {
	path := "/home/redhood/db_minor/templates/layout/nav.html"
	name := "templates/layout/nav.html"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func Asset(name string) ([]byte, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, fmt.Errorf("Asset %s not found", name)
}

// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if err != nil {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func AssetInfo(name string) (os.FileInfo, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, fmt.Errorf("AssetInfo %s not found", name)
}

// AssetNames returns the names of the assets.
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

// _bindata is a table, holding each asset generator, mapped to its name.
var _bindata = map[string]func() (*asset, error){
	"templates/cart.html":          templatesCartHtml,
	"templates/home.html":          templatesHomeHtml,
	"templates/item.html":          templatesItemHtml,
	"templates/login.html":         templatesLoginHtml,
	"templates/my_orders.html":     templatesMy_ordersHtml,
	"templates/old_cart.html":      templatesOld_cartHtml,
	"templates/register.html":      templatesRegisterHtml,
	"templates/tag_search.html":    templatesTag_searchHtml,
	"templates/layout/base.html":   templatesLayoutBaseHtml,
	"templates/layout/footer.html": templatesLayoutFooterHtml,
	"templates/layout/nav.html":    templatesLayoutNavHtml,
}

// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//     data/
//       foo.txt
//       img/
//         a.png
//         b.png
// then AssetDir("data") would return []string{"foo.txt", "img"}
// AssetDir("data/img") would return []string{"a.png", "b.png"}
// AssetDir("foo.txt") and AssetDir("notexist") would return an error
// AssetDir("") will return []string{"data"}.
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		cannonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(cannonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, fmt.Errorf("Asset %s not found", name)
			}
		}
	}
	if node.Func != nil {
		return nil, fmt.Errorf("Asset %s not found", name)
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}

type bintree struct {
	Func     func() (*asset, error)
	Children map[string]*bintree
}

var _bintree = &bintree{nil, map[string]*bintree{
	"templates": &bintree{nil, map[string]*bintree{
		"cart.html": &bintree{templatesCartHtml, map[string]*bintree{}},
		"home.html": &bintree{templatesHomeHtml, map[string]*bintree{}},
		"item.html": &bintree{templatesItemHtml, map[string]*bintree{}},
		"layout": &bintree{nil, map[string]*bintree{
			"base.html":   &bintree{templatesLayoutBaseHtml, map[string]*bintree{}},
			"footer.html": &bintree{templatesLayoutFooterHtml, map[string]*bintree{}},
			"nav.html":    &bintree{templatesLayoutNavHtml, map[string]*bintree{}},
		}},
		"login.html":      &bintree{templatesLoginHtml, map[string]*bintree{}},
		"my_orders.html":  &bintree{templatesMy_ordersHtml, map[string]*bintree{}},
		"old_cart.html":   &bintree{templatesOld_cartHtml, map[string]*bintree{}},
		"register.html":   &bintree{templatesRegisterHtml, map[string]*bintree{}},
		"tag_search.html": &bintree{templatesTag_searchHtml, map[string]*bintree{}},
	}},
}}

// RestoreAsset restores an asset under the given directory
func RestoreAsset(dir, name string) error {
	data, err := Asset(name)
	if err != nil {
		return err
	}
	info, err := AssetInfo(name)
	if err != nil {
		return err
	}
	err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
	if err != nil {
		return err
	}
	err = ioutil.WriteFile(_filePath(dir, name), data, info.Mode())
	if err != nil {
		return err
	}
	err = os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
	if err != nil {
		return err
	}
	return nil
}

// RestoreAssets restores an asset under the given directory recursively
func RestoreAssets(dir, name string) error {
	children, err := AssetDir(name)
	// File
	if err != nil {
		return RestoreAsset(dir, name)
	}
	// Dir
	for _, child := range children {
		err = RestoreAssets(dir, filepath.Join(name, child))
		if err != nil {
			return err
		}
	}
	return nil
}

func _filePath(dir, name string) string {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	return filepath.Join(append([]string{dir}, strings.Split(cannonicalName, "/")...)...)
}
